#ifndef _HW_BLUE_SCREEN_H_
#define _HW_BLUE_SCREEN_H_

#define TC_CS_DPRT		FIO0DIR
#define TC_CS_PRTS		FIO0SET
#define TC_CS_PRTC		FIO0CLR
#define TC_CS_PIN		16

#define TC_PEN_DPRT		FIO2DIR
#define TC_PEN_PRTS		FIO2SET
#define TC_PEN_PRTC		FIO2CLR
#define TC_PEN_PINP		FIO2PIN
#define TC_PEN_PIN		10

#define SD_CS_DPRT		FIO2DIR
#define SD_CS_PRTS		FIO2SET
#define SD_CS_PRTC		FIO2CLR
#define SD_CS_PIN		6

#define SD_SCLK_DPRT	FIO0DIR
#define SD_SCLK_PRTS	FIO0SET
#define SD_SCLK_PRTC	FIO0CLR
#define SD_SCLK_PIN		15

#define SD_MOSI_DPRT	FIO0DIR
#define SD_MOSI_PRTS	FIO0SET
#define SD_MOSI_PRTC	FIO0CLR
#define SD_MOSI_PIN		18

#endif
